Feature/processing data
peterdgreat/blog-app pull request #8
Opened 2022-01-18 00:22 UTC by peterdgreat

- Created model classes for all entities as shown in the ERD diagram.
- Set up associations between models.

2022-01-18 01:29 UTC, petudeveloper requested changes
Hi @peterdgreat, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

- [ ] You are missing the `Like` model inside your `app/models/`. Please add this file and add the corresponding associations with the other models in order to follow the given [ERD diagram](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png). **_Note: I add the comment here because there was no file created to add the comment._**
- [ ] Like model doesn't have a method that updates the likes counter for a post. You are missing the `Like` model, please add it and the required method. **_Note: I add the comment here because there was no file created to add the comment._**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-01-18 01:29 UTC, petudeveloper commented on app/models/post.rb
> +  has_many :likes, foreign_key: :author_id
The foreign key is improperly implemented. As per the given ERD, the Post association should have Post belong to User through Author, an alias of User, like below:
```
# app/models/post.rb
belongs_to :author, class_name: 'User'
has_many :comments
has_many :likes
```
the `foreign_key: :author_id` is not necessary. 

Kindly ensure to improve upon this aspect.

2022-01-18 01:29 UTC, petudeveloper commented on app/models/comment.rb
> +  belongs_to :post
The foreign key is improperly implemented. As per the given ERD, the Comment association should have Comment belong to User through Author, an alias of User, like below:
`belongs_to :author, class_name: 'User'`, the `foreign_key: :author_id` is not necessary.

Kindly ensure to improve upon this aspect.

2022-01-18 01:29 UTC, petudeveloper commented on app/models/post.rb
> +  end
[OPTIONAL] You can use one of the Rails Active Callbacks - after_save to call the #update_post_counter method every time a new post has been saved to database, then make the update_post_counter method private

```
  # app/models/post.rb
  after_save :update_post_counter

  private

  def update_post_counter
    # logic here
  end
```

2022-01-18 01:29 UTC, petudeveloper commented on app/models/post.rb
> +    Comment.where(post_id: id).order(created_at: :desc).limit(3)
The Post model should have a method that returns the _**5**_ most recent comments for a given post. You are returning _**3,**_ please correct this.

2022-01-18 01:29 UTC, petudeveloper commented on app/models/comment.rb
> +  end
[OPTIONAL] You can use one of the [Rails Active Callbacks](https://guides.rubyonrails.org/active_record_callbacks.html) - `after_save` to call the `#update_comments_counter` method every time a new post has been saved to database, then make the `update_comments_counter` method private

```
  # app/models/comment.rb
  after_save :update_comments_counter

  private

  def update_comments_counter
    # logic here
  end
```

2022-01-18 09:06 UTC, addod19 requested changes
### Hi @peterdgreat, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-18 09:06 UTC, addod19 commented on app/models/comment.rb
> +  belongs_to :author, class_name: 'User', foreign_key: :author_id
- [ ] It would be better if the `foreign_key: :author_id` was removed as mentioned in the previous review :man_technologist:

2022-01-18 15:50 UTC, bimbolabuari approved these changes
# Project Approved 🚀

Hi @peterdgreat 🥇,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-18 15:53 UTC, merged

2022-01-24 16:23 UTC, Dipeshtwis reviewed
Hi @peterdgreat,

## Status: Invalid ❌

While you have done a great job. I can't review this PR. Please fix the issue mentioned below and then request for code review

## Reason

- [ ] You have requested code review which is already merged. Please create another new PR with all the changes needed in this milestone.

### Please make sure to submit a code review when you are done with the changes that was requested

**Don't worry you still have same number of requests left as previous.**


Cheers and Happy Coding :clap: :clap: :clap: 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Dipesh Kumar_**